Repository Pincer-org/Pincer, pull requests merged in 2021-10, with the labels that each got.

#92 Improved the way events are executed + implemented command argument descriptions.
  pincer/client.py
  pincer/commands.py
Labels: enhancement

#94 🔖 0.7.1 Support for argument descriptions
  docs/PYPI.md
  docs/README.md
  docs/pincer.utils.rst
  examples/.gitignore
  examples/chat_commands_class_based.py
  examples/chat_commands_function_based.py
  examples/context.py
  examples/cooldowns.py
  pincer/__init__.py
  pincer/_config.py
  pincer/client.py
  pincer/commands.py
  pincer/middleware/__init__.py
  pincer/middleware/channel_create.py
  pincer/objects/__init__.py
  pincer/objects/app_command.py
  pincer/objects/application.py
  pincer/objects/attachment.py
  pincer/objects/audit_log.py
  pincer/objects/ban.py
  pincer/objects/button.py
  pincer/objects/channel.py
  pincer/objects/connection.py
  pincer/objects/embed.py
  pincer/objects/emoji.py
  pincer/objects/followed_channel.py
  pincer/objects/guild.py
  pincer/objects/guild_member.py
  pincer/objects/guild_template.py
  pincer/objects/guild_widget.py
  pincer/objects/integration.py
  pincer/objects/interaction_base.py
  pincer/objects/interactions.py
  pincer/objects/invite.py
  pincer/objects/message.py
  pincer/objects/message_component.py
  pincer/objects/message_reference.py
  pincer/objects/overwrite.py
  pincer/objects/reaction.py
  pincer/objects/role.py
  pincer/objects/select_menu.py
  pincer/objects/stage.py
  pincer/objects/sticker.py
  pincer/objects/thread.py
  pincer/objects/user.py
  pincer/objects/user_message.py
  pincer/objects/voice_state.py
  pincer/objects/webhook.py
  pincer/utils/directory.py
Labels: release

#95 Implements command choices
  docs/PYPI.md
  docs/README.md
  pincer/__init__.py
  pincer/commands.py
  pincer/objects/app_command.py
  pincer/utils/__init__.py
  pincer/utils/types.py
Labels: enhancement, Hacktoberfest

#97 🔖 `0.7.2` Adding command choices
  docs/PYPI.md
  docs/README.md
  pincer/__init__.py
  pincer/commands.py
  pincer/objects/app_command.py
  pincer/utils/__init__.py
  pincer/utils/types.py
Labels: release

#99 👷 CI for sorting `__all__` alphabetically!
  .github/workflows/docs.yml
  .github/workflows/sort_alls.yaml
  gen/all_sorter.py
  pincer/__init__.py
  pincer/objects/__init__.py
  pincer/utils/__init__.py
Labels: enhancement

#98 ✨ Implements a task system
  docs/pincer.utils.rst
  pincer/exceptions.py
  pincer/utils/__init__.py
  pincer/utils/tasks.py
Labels: enhancement, Hacktoberfest

#109 📝 Add/update a few docstrings
  pincer/commands.py
  pincer/utils/tasks.py
Labels: documentation

#113 📌 Update Pipfile
  Pipfile
Labels: dependencies

#112 :construction_worker: Adding Codecov
  .github/workflows/codecov.yml
  requirements_dev.txt
Labels: CI

#111 ✨ Added `Channel.edit`
  pincer/objects/guild/channel.py
Labels: enhancement, Hacktoberfest

#114 ✨ Created a COG system
  docs/PYPI.md
  docs/README.md
  docs/pincer.utils.rst
  examples/.gitignore
  examples/basic_cogs/cogs/error_handler.py
  examples/basic_cogs/cogs/on_ready.py
  examples/basic_cogs/cogs/say.py
  examples/basic_cogs/run.py
  pincer/__init__.py
  pincer/client.py
  pincer/commands.py
  pincer/exceptions.py
  pincer/middleware/interaction_create.py
  pincer/middleware/ready.py
  pincer/objects/app/command.py
  pincer/utils/__init__.py
  pincer/utils/extraction.py
  pincer/utils/signature.py
  pincer/utils/types.py
Labels: enhancement, Hacktoberfest

#116 🔖 0.9.0 Cogs & Channel Edition
  .github/workflows/codecov.yml
  Pipfile
  docs/PYPI.md
  docs/README.md
  docs/pincer.utils.rst
  examples/.gitignore
  examples/basic_cogs/cogs/error_handler.py
  examples/basic_cogs/cogs/on_ready.py
  examples/basic_cogs/cogs/say.py
  examples/basic_cogs/run.py
  pincer/__init__.py
  pincer/client.py
  pincer/commands.py
  pincer/exceptions.py
  pincer/middleware/interaction_create.py
  pincer/middleware/ready.py
  pincer/objects/app/command.py
  pincer/objects/guild/channel.py
  pincer/utils/__init__.py
  pincer/utils/extraction.py
  pincer/utils/signature.py
  pincer/utils/tasks.py
  pincer/utils/types.py
  requirements_dev.txt
Labels: release

#117 🔖 `0.9.0` fix
  examples/basic_cogs/cogs/on_ready.py
  examples/basic_cogs/cogs/say.py
  examples/basic_cogs/run.py
  pincer/__init__.py
  pincer/middleware/activity_join.py
Labels: release

#120 🔖 0.9.0 Cogs & Channel Edition [FULL]
  .github/workflows/codecov.yml
  Pipfile
  docs/PYPI.md
  docs/README.md
  docs/pincer.utils.rst
  examples/.gitignore
  examples/basic_cogs/cogs/error_handler.py
  examples/basic_cogs/cogs/on_ready.py
  examples/basic_cogs/cogs/say.py
  examples/basic_cogs/run.py
  pincer/__init__.py
  pincer/client.py
  pincer/commands.py
  pincer/exceptions.py
  pincer/middleware/activity_join.py
  pincer/middleware/interaction_create.py
  pincer/middleware/ready.py
  pincer/objects/app/command.py
  pincer/objects/guild/channel.py
  pincer/utils/__init__.py
  pincer/utils/extraction.py
  pincer/utils/signature.py
  pincer/utils/tasks.py
  pincer/utils/types.py
  requirements_dev.txt
Labels: documentation, enhancement, release
