Repository Pincer-org/Pincer, pull requests merged in 2021-09, with the labels that each got.

#29 Auto generate docs Github Action
  .github/workflows/docs.yml
  docs/pincer.objects.rst
  docs/pincer.utils.rst
Labels: documentation

#44 Adding main APIObjects
  pincer/core/heartbeat.py
  pincer/exceptions.py
  pincer/objects/__init__.py
  pincer/objects/application.py
  pincer/objects/application_command.py
  pincer/objects/attachment.py
  pincer/objects/audit_log.py
  pincer/objects/ban.py
  pincer/objects/button.py
  pincer/objects/channel.py
  pincer/objects/embed.py
  pincer/objects/emoji.py
  pincer/objects/followed_channel.py
  pincer/objects/guild.py
  pincer/objects/guild_member.py
  pincer/objects/guild_template.py
  pincer/objects/guild_widget.py
  pincer/objects/integration.py
  pincer/objects/intents.py
  pincer/objects/interactions.py
  pincer/objects/invite.py
  pincer/objects/message.py
  pincer/objects/message_component.py
  pincer/objects/message_reference.py
  pincer/objects/overwrite.py
  pincer/objects/reaction.py
  pincer/objects/role.py
  pincer/objects/select_menu.py
  pincer/objects/stage.py
  pincer/objects/sticker.py
  pincer/objects/thread.py
  pincer/objects/user.py
  pincer/objects/voice_region.py
  pincer/objects/voice_state.py
  pincer/objects/webhook.py
  pincer/objects/welcome_screen.py
  pincer/utils/api_object.py
  pincer/utils/constants.py
  pincer/utils/snowflake.py
  pincer/utils/timestamp.py
Labels: documentation, enhancement, help wanted

#53 🐛 Bug with APINullable
  pincer/utils/constants.py
Labels: bug

#62 ✨ Added gateway events
  docs/pincer.objects.rst
  pincer/events/channel.py
  pincer/events/gateway_commands.py
  pincer/events/guild.py
  pincer/events/hello_ready.py
  pincer/events/integration.py
  pincer/events/invite.py
  pincer/events/message.py
  pincer/events/presence.py
  pincer/events/thread.py
  pincer/events/typing_start.py
  pincer/events/voice.py
  pincer/events/webhook.py
  pincer/objects/guild.py
  pincer/objects/session_start_limit.py
  pincer/objects/thread.py
Labels: enhancement

#63 ♻️ Use one instance of HttpClient for all requests
  pincer/client.py
  pincer/commands.py
  pincer/core/gateway.py
Labels: enhancement

#64 Documentation Update
  docs/conf.py
  docs/quickstart.rst
Labels: documentation

#68 ✨Guild Object with Client.get_guild
  pincer/client.py
  pincer/middleware/__init__.py
  pincer/objects/channel.py
  pincer/objects/guild.py
Labels: enhancement

#70 Yieldable commands
  pincer/commands.py
  pincer/core/http.py
  pincer/middleware/interaction_create.py
Labels: enhancement

#71 🐛 Added member to MessageInteraction
  pincer/objects/interaction_base.py
Labels: bug

#73 Methods to Guild and User
  pincer/client.py
  pincer/middleware/error.py
  pincer/middleware/interaction_create.py
  pincer/middleware/message_create.py
  pincer/middleware/message_delete.py
  pincer/middleware/ready.py
  pincer/objects/channel.py
  pincer/objects/guild.py
  pincer/objects/guild_member.py
  pincer/objects/interactions.py
  pincer/objects/user.py
  pincer/objects/user_message.py
  pincer/utils/api_object.py
  pincer/utils/conversion.py
Labels: enhancement

#79 🔖 Releasing `0.7.0dev0`
  .editorconfig
  .github/workflows/pypi_upload.yaml
  docs/PYPI.md
  docs/README.md
  docs/pincer.objects.rst
  examples/cooldowns.py
  gen/setup_generator.py
  goals/command.md
  pincer/__init__.py
  pincer/client.py
  pincer/commands.py
  pincer/core/http.py
  pincer/exceptions.py
  pincer/middleware/__init__.py
  pincer/middleware/error.py
  pincer/middleware/interaction_create.py
  pincer/middleware/message_create.py
  pincer/middleware/message_delete.py
  pincer/middleware/ready.py
  pincer/objects/__init__.py
  pincer/objects/app_command.py
  pincer/objects/context.py
  pincer/objects/embed.py
  pincer/objects/guild.py
  pincer/objects/guild_member.py
  pincer/objects/interactions.py
  pincer/objects/message.py
  pincer/objects/message_context.py
  pincer/objects/throttle_scope.py
  pincer/objects/throttling.py
  pincer/objects/user.py
  pincer/objects/user_message.py
  pincer/utils/conversion.py
  pincer/utils/insertion.py
  pincer/utils/slidingwindow.py
  setup.cfg
  setup.py
Labels: release
