Repository Pincer-org/Pincer, pull requests merged in 2021-12, with the labels that each got.

#285 :art: Improving overall Pincer objects representation
  pincer/_config.py
  pincer/core/ratelimiter.py
  pincer/objects/app/application.py
  pincer/objects/app/command.py
  pincer/objects/app/intents.py
  pincer/objects/app/interaction_base.py
  pincer/objects/app/interactions.py
  pincer/objects/app/mentionable.py
  pincer/objects/app/select_menu.py
  pincer/objects/app/session_start_limit.py
  pincer/objects/events/activity.py
  pincer/objects/events/channel.py
  pincer/objects/events/error.py
  pincer/objects/events/gateway_commands.py
  pincer/objects/events/guild.py
  pincer/objects/events/hello_ready.py
  pincer/objects/events/integration.py
  pincer/objects/events/invite.py
  pincer/objects/events/message.py
  pincer/objects/events/notification.py
  pincer/objects/events/presence.py
  pincer/objects/events/thread.py
  pincer/objects/events/typing_start.py
  pincer/objects/events/voice.py
  pincer/objects/events/voice_settings.py
  pincer/objects/events/webhook.py
  pincer/objects/guild/audit_log.py
  pincer/objects/guild/ban.py
  pincer/objects/guild/channel.py
  pincer/objects/guild/followed_channel.py
  pincer/objects/guild/guild.py
  pincer/objects/guild/invite.py
  pincer/objects/guild/member.py
  pincer/objects/guild/overwrite.py
  pincer/objects/guild/role.py
  pincer/objects/guild/stage.py
  pincer/objects/guild/template.py
  pincer/objects/guild/thread.py
  pincer/objects/guild/webhook.py
  pincer/objects/guild/welcome_screen.py
  pincer/objects/guild/widget.py
  pincer/objects/message/attachment.py
  pincer/objects/message/button.py
  pincer/objects/message/component.py
  pincer/objects/message/context.py
  pincer/objects/message/embed.py
  pincer/objects/message/emoji.py
  pincer/objects/message/file.py
  pincer/objects/message/message.py
  pincer/objects/message/reaction.py
  pincer/objects/message/reference.py
  pincer/objects/message/sticker.py
  pincer/objects/message/user_message.py
  pincer/objects/user/connection.py
  pincer/objects/user/integration.py
  pincer/objects/user/user.py
  pincer/objects/user/voice_state.py
  pincer/objects/voice/region.py
  pincer/utils/api_object.py
  pincer/utils/color.py
Labels: enhancement

#275 ✨ Add more guild methods
  pincer/objects/guild/__init__.py
  pincer/objects/guild/channel.py
  pincer/objects/guild/guild.py
Labels: enhancement

#292 :sparkles: Added sticker support
  pincer/client.py
  pincer/objects/guild/guild.py
  pincer/objects/message/file.py
  pincer/objects/message/sticker.py
Labels: enhancement

#306 🐛 Transform `message.edit` list of APIObject to JSONSerializable
  pincer/objects/message/user_message.py
Labels: bug

#313 :memo: added mermaid support to docs
  .gitignore
  docs/conf.py
  docs/requirements.txt
Labels: documentation

#316 :sparkles: Added `Channel.bulk_delete_messages()` and `Channel.edit_permissions()`
  pincer/objects/guild/channel.py
Labels: enhancement

#299 🎉 Added all user and current user methods
  pincer/client.py
  pincer/objects/guild/channel.py
Labels: enhancement

#315 :sparkles: Added UserMessage.from_id
  pincer/client.py
  pincer/objects/message/user_message.py
  pincer/utils/conversion.py
Labels: enhancement

#337 :sparkles: Added 12 endpoints to `Channel`
  pincer/objects/guild/channel.py
  pincer/objects/guild/guild.py
Labels: enhancement
