Repository Pincer-org/Pincer, pull requests merged in 2021-11, with the labels that each got.

#169 ✅ Improve test coverage for core/Heartbeat.py (#121)
  Pipfile
  tests/core/test_heartbeat.py
  tests/requirements.txt
  tests/utils.py
Labels: enhancement

#167 ✨ 🐛 new interaction features, bugfix and refactor
  docs/PYPI.md
  docs/README.md
  pincer/client.py
  pincer/core/gateway.py
  pincer/core/heartbeat.py
  pincer/exceptions.py
  pincer/middleware/interaction_create.py
  pincer/objects/app/command.py
  pincer/objects/app/interactions.py
  pincer/objects/guild/member.py
  pincer/objects/message/context.py
  pincer/utils/convert_message.py
  pincer/utils/timestamp.py
Labels: bug, enhancement

#179 🐛 Pillow images can be sent in an interaction
  pincer/objects/app/interactions.py
  pincer/objects/message/message.py
Labels: bug

#163 :sparkles: Middleware addition
  pincer/middleware/channel_delete.py
  pincer/middleware/channel_pins_update.py
  pincer/middleware/channel_update.py
  pincer/middleware/guild_delete.py
  pincer/middleware/guild_update.py
  pincer/middleware/message_reaction_add.py
  pincer/middleware/message_reaction_remove.py
  pincer/middleware/message_reaction_remove_all.py
  pincer/middleware/message_reaction_remove_emoji.py
  pincer/middleware/thread_create.py
  pincer/middleware/thread_delete.py
  pincer/middleware/thread_list_sync.py
  pincer/middleware/thread_member_update.py
  pincer/middleware/thread_members_update.py
  pincer/middleware/thread_update.py
  pincer/objects/events/channel.py
  pincer/objects/guild/__init__.py
  pincer/objects/guild/guild.py
  pincer/objects/message/emoji.py
Labels: enhancement

#176 ✨ Added Client.wait_for() and Client.loop_for()
  examples/guessing_game.py
  pincer/client.py
  pincer/commands.py
  pincer/core/http.py
  pincer/exceptions.py
  pincer/utils/__init__.py
  pincer/utils/event_mgr.py
  pincer/utils/types.py
Labels: enhancement

#225 :sparkles: Added client and guild methods, GuildPreview object
  pincer/client.py
  pincer/objects/guild/guild.py
Labels: enhancement

#235 :sparkles: Closes 186, 201, 203, and 216.
  pincer/client.py
  pincer/objects/guild/channel.py
  pincer/objects/guild/guild.py
  pincer/objects/guild/role.py
  pincer/objects/message/context.py
  pincer/objects/user/user.py
  pincer/utils/__init__.py
  pincer/utils/color.py
  tests/utils/test_color.py
Labels: bug, enhancement

#243 :construction_worker: Create python-publish.yml
  .github/workflows/pypi_upload.yaml
  .github/workflows/python-publish.yml
Labels: enhancement

#226 🧪 Added a test to check for Guild deserialization and made the test passing
  pincer/objects/app/command.py
  pincer/objects/app/interactions.py
  pincer/utils/api_object.py
  pincer/utils/conversion.py
  pyproject.toml
  tests/objects/guild/test_guild.py
  tests/requirements.txt
Labels: tests

#238 :sparkles: Added role and ban related Guild methods
  pincer/objects/guild/guild.py
Labels: enhancement

#248 :sparkles: Added remaining Guild methods
  pincer/objects/guild/guild.py
  pincer/utils/conversion.py
  pincer/utils/types.py
  tests/utils/test_convertion.py
Labels: documentation, enhancement

#246 :boom: Better command types and application command types
  docs/PYPI.md
  docs/README.md
  docs/api.rst
  docs/pincer.commands.rst
  docs/pincer.rst
  examples/chat_commands_class_based.py
  examples/chat_commands_function_based.py
  examples/context.py
  examples/cooldowns.py
  examples/guessing_game.py
  pincer/__init__.py
  pincer/commands/__init__.py
  pincer/commands/arg_types.py
  pincer/commands/commands.py
  pincer/middleware/interaction_create.py
  pincer/objects/app/command.py
  pincer/objects/guild/member.py
  pincer/objects/message/user_message.py
  pincer/utils/__init__.py
  pincer/utils/api_object.py
  pincer/utils/types.py
Labels: enhancement

#241 :children_crossing: new example with PIL
  .gitignore
  examples/tweet_generator/tweet_generator.py
  pincer/objects/user/user.py
Labels: enhancement

#267 :sparkles: Added Audit Log and Emoji related Guild methods
  pincer/commands/arg_types.py
  pincer/objects/guild/guild.py
Labels: enhancement
